CREATE DATABASE IF NOT EXISTS `List` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT  INSERT,SELECT,UPDATE ON `List`.* TO 'user1'@'%';

CREATE TABLE `List`.`Connection`(
	ID  INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, /* 入力idx */
	ipaddr    INTEGER UNSIGNED NOT NULL,  /* IPアドレス */
	name      VARCHAR(30) NOT NULL        /* マシン名 */
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `List`.`MIBNodeOIDNumber`(
	ID  INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, /* 入力idx */
	oid       VARCHAR(50) NOT NULL,       /* OID番号 */
	name      VARCHAR(30) NOT NULL        /* マシン名 */
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `List`.`Combination`(
	ID  INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, /* 入力idx */
	ipaddridx INTEGER UNSIGNED NOT NULL,  /* IPアドレス */
	oididx    INTEGER UNSIGNED NOT NULL,  /* マシン名 */
	FOREIGN KEY (ipaddridx) REFERENCES `List`.`Connection`(ID),
	FOREIGN KEY (oididx)    REFERENCES `List`.`MIBNodeOIDNumber`(ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

