version: '3'
services:
  web:
    build: 
      context: './server'
      dockerfile: 'web-Dockerfile'
    hostname: "web_server"
    networks:
      backend:
        ipv4_address: 10.0.1.2
    volumes:
      - './server/web:/usr/local/apache2/htdocs/'
    ports:
      - '40080:80'
    depends_on: 
      - "mysql"
  
  api:
    build: 
      context: './server'
      dockerfile: 'api-Dockerfile'
    hostname: "api_server"
    networks:
      backend:
        ipv4_address: 10.0.1.3
    volumes:
      - './server/api:/usr/local/apache2/htdocs/'
    ports:
      - '40081:80'
    depends_on: 
      - "mysql"
    # tty: true
      
  mysql:
    image: mysql:5.7
    hostname: "linux_mysql"
    networks:
      backend:
        ipv4_address: 10.0.1.10
    volumes:
       - "./server/mysql/initdb:/docker-entrypoint-initdb.d"
      #  - "./srv/mysql/db_data/:/var/lib/mysql"
       - "./server/mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: password2018
    ports:
      - '43306:3306'
    expose:
      - "3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - "40082:80"
    hostname: "linux_phpmyadmin"
    networks:
      backend:
        ipv4_address: 10.0.1.11
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password2018
    depends_on:
      - "mysql"
    links:
      - mysql

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.0.1.0/24
