version: '3'
services:
  # test:
  #   build: 
  #     context: ./test
  #   hostname: "linux_test"
  #   networks:
  #     backend:
  #       ipv4_address: 10.0.1.16
  #   volumes: 
  #     - "./test/src:/src"
  #   tty: true
  
  client:
    build:
      context: ./client
    hostname: "linux_client"
    volumes: 
      #- './client/src:/src'
      - '/proc/stat:/srv/proc/stat:ro'
    pid: "host"
    #tty: true
    network_mode: host

      
