version: '3'
services:
  server:
    # images: php:7-apache
    build: 
      context: ./server
    hostname: "linux_server"
    networks:
      backend:
        ipv4_address: 10.0.1.2
    volumes: 
      - './server/src:/usr/local/apache2/htdocs/'
    ports:
      - '40080:80'
    depends_on: 
      - "mysql"
  
  mysql:
    image: mysql:5.7
    hostname: "linux_mysql"
    networks:
      backend:
        ipv4_address: 10.0.1.3
    volumes:
       - "./srv/mysql/initdb:/docker-entrypoint-initdb.d"
      #  - "./srv/mysql/db_data/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password2018
    expose:
      - "3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - "40081:80"
    hostname: "linux_phpmyadmin"
    networks:
      backend:
        ipv4_address: 10.0.1.4
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password2018
    depends_on:
      - "mysql"
    links:
      - mysql

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.0.1.0/24